/*
 * This source file was generated by the Gradle 'init' task
 */
package funciona;

import java.util.Scanner;

public class App {
    public String getGreeting() {
		return "Hello World!";
	}

	public static void batalha(Scanner scanner) {
        System.out.println("\n----------------------");
		System.out.println("- ESCOLHA DE PERSONAGENS -");
		System.out.println("Escolha seu personagem! [1- Guerreiro] [2- Mago] [3- Arqueiro]");
		int defPerso = scanner.nextInt();
        scanner.nextLine();
		
		System.out.println("Digite o nome do seu personagem: ");
        String nome = scanner.nextLine();
		Personagem player = (defPerso == 1) ? new Guerreiro(nome)
				: (defPerso == 2) ? new Mago(nome) 
				: new Arqueiro(nome);

		

        System.out.println("|----------------------|");
		System.out.println("Escolha seu inimigo! [1- Guerreiro] [2- Mago] [3- Arqueiro]");
		int defInimigo = scanner.nextInt();
		scanner.nextLine();
		Personagem inimigo = (defInimigo == 1) ? new Guerreiro("Jovialdo")
				: (defInimigo == 2) ? new Mago("Gandalf Roberto") 
                : new Arqueiro("Lula Inacio da Silva");

		while (player.estaVivo() && inimigo.estaVivo()) {
            System.out.println("\n |------------------------|");
            System.out.println("------ BATALHA --------");
            System.out.println("| - - - - - - - - - - |");
            System.out.println("| STATUS DO JOGADOR |");
            System.out.println("- " + player.getNome());
            System.out.println("- Hp:" + player.getVida());
			System.out.println("Escolha: [atacar]");
			String opcPlayer = scanner.nextLine().toLowerCase();

            switch (opcPlayer) {
                case "atacar":
                        player.atacar(inimigo);
                        System.out.println("| - - - - - - - - - - |");
                        System.out.println("| STATUS DO OPONENTE |");
                        System.out.println("- " + inimigo.getNome());
                        System.out.println("- Hp:" + inimigo.getVida());
                    break;
            
                default:
                    break;
            }

            System.out.println(!inimigo.estaVivo() ? "Você ganhou!" : "");


		}


	}

	public static void main(String[] args) {
		Scanner scanner = new Scanner(System.in);
		
		batalha(scanner);
		
		scanner.close();
	}
}
